### ISSUE TITLE
Cannot drag'n'drop metadata onto a nwk tree

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/auspice.us#10] opened 2021-02-13 00:31 UTC
**Current Behavior**  
When a .nwk tree is loaded onto auspice, I am unable to drag'n'drop a tsv with metadata. It results in a blank screen.  I can drag'n'drop metadata onto a Nextstrain (.json) tree though.

**Expected behavior**  
Should be able to layer metadata on a nwk tree in.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Go to https://auspice.us/
2. Upload .nwk tree
3. Drag 'n' drop tsv containing metadata for tips in the .nwk tree
4. See blank screen

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Windows 10 Pro
 - Browser:  Chrome

**Additional context**  
Thanks to @allenkj2 for flagging this behavior!

**Comment by LiXingguangBrandonStark** [comment] 2021-03-14 07:59
I  CAN NOT DROP THE NEWICK TREE, WHO CAN HELP ME , THANKS.

**Comment by Joseph7e** [comment] 2021-05-05 01:11
Is there a fix for this yet?

**Comment by jameshadfield** [comment] 2022-02-23 00:08
I cannot reproduce this error -- using the following files (small newick tree, CSV metadata file or TSV metadata file) I can correctly load metadata via drag-and-drop. Please reopen this if it's still not working for you, and if you could provide test files where it doesn't work that would be really helpful!

[test_newick_metadata.zip](https://github.com/nextstrain/auspice.us/files/8121006/test_newick_metadata.zip)

**Closed by jameshadfield** 2022-02-23 00:08 UTC
Labels: bug

**Comment by cassiawag** [comment] 2022-03-04 00:22
I also can't replicate this behavior anymore either, James.
